### PR TITLE
Treatment query

### PR DESCRIPTION
**Pull request by popkinj**
# Area to be Treated Query
This contains new sql files for:
1. Area treated
2. Observations that have yet to be treated.
Both have be written to work well with Metabase.

### CODE REVIEW

**Comment by micheal-w-wells** [comment]
rebased to make PR review easier (4 changed files instead of 42)

**Review by micheal-w-wells — APPROVED** [review]

**Comment by popkinj** [comment]
I did rebase this though.

**Comment by micheal-w-wells** [comment]
you merged dev into your branch from what I could see, that's why it showed all those other commits since the branch was checked out

**Comment by micheal-w-wells** [comment]
you also might not have pulled down up to date dev when you did the rebase

**Comment by popkinj** [comment]
That's weird... this is what I did
```bash
git checkout dev
git pull
git checkout treatment-query
git rebase dev
git pull --rebase
git push
```
Do you see any red flags?

**Comment by micheal-w-wells** [comment]
yes.  don't ```git pull --rebase``` after rebasing your branch.  you just need to force push to update the remote.

This was right:
```
git checkout dev
git pull
git checkout treatment-query
git rebase dev
```

Then you needed to ```git push origin treatment-query --force```.

**Comment by popkinj** [comment]
Aaahh. Got it.

**Pull request merged**
