### PR TITLE
268: UI for Treatment data alongside Monitoring

### LINKED ISSUE #268: UI for monitoring
**Describe the task**
Creation of a page for read only treatment data alongside monitoring form. Come up with options and present to @mikeshasko (accordions, tabs etc.)

### PR DESCRIPTION
**Pull request by sdevalapurkar**
# Overview

This PR includes the following proposed change(s):

- UI for Treatment data alongside Monitoring
- #268 
- currently it will display the linked activity form and photos (if any exist) and no editable actions allowed on the linked record
- only main form, photos, and map is editable

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Locally

## Screenshots

sss

### CODE REVIEW

**Comment by sdevalapurkar** [comment]
@mikeshasko this is the first pass design and feature implementation
can be revisited in new year and made fancier/reworked to better suit workflows if required. Thank you!

**Review by rstens — CHANGES_REQUESTED** [review]
It looks like you have one error reported on "Remove log", can you take a look at that?

**Comment by sdevalapurkar** [comment]
> It looks like you have one error reported on "Remove log", can you take a look at that?

which error roland? I dont see the one you are referring to

**Comment by rstens** [comment]
https://github.com/bcgov/invasivesbc/pull/299/commits/22e53ffc85ea3835ed0d6869ea30c17e53ec4a85
failure on line 38?

**Comment by sdevalapurkar** [comment]
that is an older commit :)

**Review by rstens — APPROVED** [review]

**Review by dogcomplex — APPROVED** [review]
Code looking good to me, though might want to get Roland's take.  Just in case though: 👍

**Comment by sdevalapurkar** [comment]
> Code looking good to me, though might want to get Roland's take. Just in case though: 👍

looks like he has approved too :) will merge

**Pull request merged**
