### PR TITLE
Autocomplete widget (multi and single select)

### PR DESCRIPTION
**Pull request by dogcomplex**
# Overview

Adds necessary infrastructure to be able to complete:

- https://github.com/bcgov/invasivesbc/issues/251
- https://github.com/bcgov/invasivesbc/issues/645

Uses the widget from Biohub, with modifications to allow for single-select behavior as well.

UPDATE:

- Finally works!!  What a quagmire.
- Applied the widget to most of the other forms, though might have missed some (can add them as we see fit)
- All you need to do is add "'ui:widget': 'single-select-autocomplete'" to the base UI for any field you want

## Type of change

- [X] New feature (non-breaking change which adds functionality)
- [X] Refactoring / Documentation

if your change is a breaking change, please add `breaking change` label to this PR

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Screenshots

Please add any relevant UI screenshots if applicable.

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have made corresponding changes to the documentation
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by dogcomplex** [comment]
Pushed up last state before I give up here.  I can't figure out what's wrong -  even with a controlled state setting the value explicitly (and correctly, as far as I can tell) it's still triggering "should be string" errors when the form is checked for errors, and it's throwing a bunch of undefined bounces on getOptionLabel which really shouldn't be happening.  I give up (for now?), slash I'm requesting a new pair of eyes on the problem - I give up, too much time wasted on magic React classes and magic OpenAPI error handling.

**Comment by micheal-w-wells** [comment]
@dogcomplex should we get this one merged or hold out until you are done the new version?  Also would be helpful if you could open vscode and cmd+shift+p+enter and format stuff for the linter (or set it up for sublime), takes a lot of noise out of a pr review.

**Comment by dogcomplex** [comment]
So, only remaining issues here are just from the test file I copied directly from Biohub - not particularly concerned there.  If you think this is good, feel free to squash and merge!

**Review by micheal-w-wells — APPROVED** [review]

**Comment by micheal-w-wells** [comment]
merge away champ

**Pull request merged**
