### PR TITLE
Offline map

### PR DESCRIPTION
**Pull request by popkinj**
Geometries persist offline

### CODE REVIEW

**Review by rstens — COMMENTED** [review]
So why did you go to an older version of leaflet-draw?

**Review by rstens — CHANGES_REQUESTED** [review]
There are some complaints about no new-lines at the end of several files.

**Review by rstens — COMMENTED** [review]
As a general comment, when I pull this branch down and built it locally, it was/is based on a rather old earlier version. This could cause issue when merging. So I'd like to suggest that you test the new code first with a rebased branch, so that we do not find issues later.

**Comment by popkinj** [comment]
Good idea. I'll do a rebase.

**Comment by popkinj** [comment]
Hey @NickPhura and @rstens  . Can one of you check this PR. I've just made a couple adjustments. Rebase and removing code smells.

**Review by rstens — APPROVED** [review]

**Comment by popkinj** [comment]
Thanks @rstens :)

**Pull request merged**
